=== ARGOeu/gocdb/config/RoleActionMappingsSchema.xsd
<?xml version="1.0"?>
<!--
/*
* Copyright (C) 2015 STFC
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
* http://www.apache.org/licenses/LICENSE-2.0
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
@author David Meredith 
--> 

<xs:schema targetNamespace="http://goc.egi.eu/2015/03/spec1.0_r1" 
           version="1.0"
           xmlns="http://www.w3.org/2001/XMLSchema"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:goc="http://goc.egi.eu/2015/03/spec1.0_r1" 
           elementFormDefault="qualified"
           attributeFormDefault="unqualified"> 

    <xs:element name="RoleActionMappingRules">
        <annotation>
            <documentation>
        <![CDATA[
        <RoleActionMappingRules> is the root element. 
        It defines zero or more <RoleActionMapping>s, one for each project. 
        
        Each <RoleActionMapping> declares mappings between role names and the actions 
        they grant over the specified target object types.  
        
        If a <RoleActionMapping> is not specified for a particular project, 
        a single default <RoleActionMapping> MAY be defined as a fallback 
        (this default <RoleActionMapping> will define NO <TargetProject> element). 
        ]]>
            </documentation>
        </annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="goc:RoleActionMapping" minOccurs="0" maxOccurs="unbounded"></xs:element> 
            </xs:sequence>
        </xs:complexType> 
        <xs:unique name="testRoleActionMappingTargetProjectUnique">
            <xs:annotation>
                <xs:documentation>
                <![CDATA[ 
                Declares a unique constraint on the value of <TargetProject> 
                to ensure only ONE <RoleActionMapping> applies to a particular project. 
                ]]>
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="goc:RoleActionMapping/goc:TargetProject"/>
            <xs:field xpath="."/>
        </xs:unique>
    </xs:element>
    
    <xs:element name="RoleActionMapping">
        <xs:annotation>
            <xs:documentation>
            <![CDATA[ 
            Defines the role-to-action mappings for a set of projects named by
            the nested <TargetProject> elements. The basic structure of the 
            element is as follows: 
            
            <RoleActionMapping> 
                <TargetProject/> (0..*) 
                <RoleNames/>     (0..*) 
                <RoleMapping/>   (0..*)   
            </RoleActionMapping> 
            
            ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="TargetProject" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>
                <![CDATA[ 
                 Optional; used to name which project(s) this <RoleActionMapping> applies to. 
                 There can be only one <RoleActionMapping> that does not define any 
                 <TargetProject> elements, and this serves as the default. 
                ]]>
                        </xs:documentation> 
                    </xs:annotation>
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <!--<xs:attribute name="value" type="xs:string"/>-->
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>  
                </xs:element>
                <xs:element ref="goc:RoleNames" minOccurs="0" maxOccurs="unbounded"></xs:element> 
                <xs:element ref="goc:RoleMapping" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <!--<xs:attribute name="forProjects" type="string"/>-->
        </xs:complexType> 
        <!-- 
        Ensure that Role values are unique within the context of any single RoleActionMapping. 
        This allows different RoleActionMapping elements to define the same Role values.   
        -->
        <xs:unique name="testRolesUniqueInRoleActionMapping">
            <xs:selector xpath="goc:RoleNames/goc:Role"/>
            <xs:field xpath="."/>
        </xs:unique>
        <!--<xs:unique name="testRoleAliasUniqueInRoleActionMapping">
            <xs:selector xpath="goc:RoleNames/goc:Role"/>
            <xs:field xpath="@alias"/>
        </xs:unique>-->
    </xs:element>

    <xs:element name="RoleNames">
        <xs:annotation>
            <xs:documentation>
            <![CDATA[ 
            Defines the role names that apply 'over' a specified object type by 
            nesting zero or more <Role> elements. 
            ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Role" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>
                <![CDATA[ 
                Defines a role name as the element value, and an id attribute 
                that is used as a shortcut to reference this role name. 
                ]]>
                        </xs:documentation> 
                    </xs:annotation>
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="id" type="xs:ID">
                                </xs:attribute>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element> 
            </xs:sequence>    
            <xs:attribute name="over" type="string"/>
        </xs:complexType> 
    </xs:element>
  
    <element name="RoleMapping">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                Used to specify which roles enable a set of actions over the 
                specified target object(s), i.e. it actually defines 
                the role-to-action mapping. 
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <complexType>
            <sequence>
                <!-- Inline Roles element -->
                <xs:element name="Roles">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="RoleRef" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="idRef" type="xs:IDREF" use="required" />
                                </xs:complexType> 
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType> 
                </xs:element>
                <element name="EnabledActions" minOccurs="0" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="Actions">
                                <xs:annotation>
                                    <xs:documentation>
                <![CDATA[ ]]>
                                    </xs:documentation> 
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Action" minOccurs="0" maxOccurs="unbounded">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[a-zA-Z0-9_\s]+"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </element>
                            <element name="Target" minOccurs="1" maxOccurs="unbounded">
                                <xs:annotation>
                                    <xs:documentation>
                <![CDATA[ ]]>
                                    </xs:documentation> 
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>  
                            </element>
                        </sequence>
                    </complexType> 
                </element>  
            </sequence> 
        </complexType>
    </element>

</xs:schema>

=== ARGOeu/gocdb/config/RoleActionMappingsOld.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/*
* Copyright (C) 2015 STFC
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
* http://www.apache.org/licenses/LICENSE-2.0
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
-->


<RoleActionMappingRules     
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://goc.egi.eu/2015/03/spec1.0_r1'
    xsi:schemaLocation='http://goc.egi.eu/2015/03/spec1.0_r1 ./RoleActionMappingsSchema.xsd'> 

    

    <RoleActionMapping> 
        <TargetProject>EGI</TargetProject> 

        <!-- 
        Define the Role names and which of the owned entity types they apply to. 
        Note, role name and alias values must be unique (names have a DB unique constraint).  
        Aliases are used as a convenient shorthand to define the XML rules. 
        --> 
        <RoleNames over="Project">
            <Role alias="COD_STAFF">COD Staff</Role>
            <Role alias="COD_ADMIN">COD Administrator</Role>
            <Role alias="EGI_CSIRT_OFFICER">EGI CSIRT Officer</Role>
            <Role alias="COO">Chief Operations Officer</Role>
        </RoleNames>  


        <RoleNames over="Ngi">
            <Role alias="NGI_OPS_MAN">NGI Operations Manager</Role>
            <Role alias="NGI_OPS_DEP_MAN">NGI Operations Deputy Manager</Role>
            <Role alias="NGI_SEC_OFFICER">NGI Security Officer</Role>
            <Role alias="REG_STAFF_ROD">Regional Staff (ROD)</Role>
            <Role alias="REG_FIRST_LINE_SUPPORT">Regional First Line Support</Role>
        </RoleNames>

        <RoleNames over="Site"> 
            <Role alias="SITE_ADMIN">Site Administrator</Role>
            <Role alias="SITE_SECOFFICER">Site Security Officer</Role>
            <Role alias="SITE_OPS_DEP_MAN">Site Operations Deputy Manager</Role>
            <Role alias="SITE_OPS_MAN">Site Operations Manager</Role>
        </RoleNames> 

        <RoleNames over="ServiceGroup">
            <Role alias="SERVICE_GROUP_ADMIN">Service Group Administrator</Role>
        </RoleNames>


        <!--
        The listed Roles enable the Actions over the target object(s). 
        --> 

        <RoleMapping>
            <Roles>
                COD_STAFF,
                COD_ADMIN,
                EGI_CSIRT_OFFICER,
                COO
            </Roles>  
            <EnabledActions>
                <Actions>ACTION_EDIT_OBJECT,ACTION_GRANT_ROLE,ACTION_REJECT_ROLE,ACTION_REVOKE_ROLE</Actions> 
                <Target>Project</Target> 
            </EnabledActions>
            <EnabledActions>
                <Actions>ACTION_GRANT_ROLE,ACTION_REJECT_ROLE,ACTION_REVOKE_ROLE</Actions>
                <Target>Ngi</Target>
            </EnabledActions>
        </RoleMapping>

        <RoleMapping>
            <Roles>
                NGI_OPS_MAN,
                NGI_OPS_DEP_MAN,
                NGI_SEC_OFFICER,
                REG_STAFF_ROD,
                REG_FIRST_LINE_SUPPORT
            </Roles>
            <EnabledActions>
                <Actions>ACTION_EDIT_OBJECT</Actions>
                <Target>Ngi</Target>
            </EnabledActions>
        </RoleMapping>

        <RoleMapping>
            <Roles>
                NGI_OPS_MAN,
                NGI_OPS_DEP_MAN,
                NGI_SEC_OFFICER
            </Roles>
            <EnabledActions>
                <Actions>ACTION_NGI_ADD_SITE,ACTION_GRANT_ROLE,ACTION_REJECT_ROLE,ACTION_REVOKE_ROLE</Actions>
                <Target>Ngi</Target>
            </EnabledActions>
        </RoleMapping>

        <RoleMapping> 
            <Roles>
                SITE_ADMIN, 
                SITE_SECOFFICER, 
                SITE_OPS_DEP_MAN, 
                SITE_OPS_MAN
                REG_FIRST_LINE_SUPPORT, 
                REG_STAFF_ROD, 
                NGI_SEC_OFFICER, 
                NGI_OPS_DEP_MAN, 
                NGI_OPS_MAN 
            </Roles>  
            <EnabledActions> 
                <Actions>ACTION_EDIT_OBJECT, ACTION_SITE_ADD_SERVICE, ACTION_SITE_DELETE_SERVICE</Actions> 
                <Target>Site</Target>   
            </EnabledActions> 
        </RoleMapping> 


        <RoleMapping> 
            <Roles>
                SITE_SECOFFICER, 
                SITE_OPS_DEP_MAN, 
                SITE_OPS_MAN
                NGI_SEC_OFFICER, 
                NGI_OPS_DEP_MAN, 
                NGI_OPS_MAN 
            </Roles> 
            <EnabledActions> 
                <Actions>ACTION_GRANT_ROLE, ACTION_REJECT_ROLE, ACTION_REVOKE_ROLE</Actions> 
                <Target>Site</Target>   
            </EnabledActions> 
        </RoleMapping> 

 
        <RoleMapping> 
            <Roles>
                NGI_SEC_OFFICER, 
                NGI_OPS_DEP_MAN, 
                NGI_OPS_MAN  
                COD_STAFF,
                COD_ADMIN,
                EGI_CSIRT_OFFICER,
                COO
            </Roles>  
            <EnabledActions> 
                <Actions>ACTION_SITE_EDIT_CERT_STATUS</Actions> 
                <Target>Site</Target>   
            </EnabledActions> 
        </RoleMapping> 


        <RoleMapping>
            <Roles>SERVICE_GROUP_ADMIN</Roles>
            <EnabledActions>
                <Actions>ACtion_EDIT_OBJECT,ACTION_GRANT_ROLE, ACTION_REJECT_ROLE, ACTION_REVOKE_ROLE</Actions>
                <Target>SERviceGroup</Target> 
            </EnabledActions>
        </RoleMapping>

        <!-- 
        For the newly proposed edit NGI cert status: 
        <RoleMapping> 
           <Roles>
               COD_STAFF,
               COD_ADMIN,
               EGI_CSIRT_OFFICER,
               COO
           </Roles>  
           <EnabledActions> 
             <Actions>ACTION_NGI_EDIT_CERT_STATUS</Actions> 
             <Target>Ngi</Target>   
           </EnabledActions> 
        </RoleMapping> 
        -->
 
    </RoleActionMapping> 

</RoleActionMappingRules>
